### ISSUE TITLE
Feature: People select clothes color and skin tone.

### ISSUE THREAD

**Issue by rav3n11** [rav3n11/lego-minifig-generator#3]
SO... The plan is to allow people to select clothes color. The frontend is getting ready to implement this feature.
We need: 

- routes that allow for color requests for each section, creates an SVG and sends it.

**Comment by zaahmed-nisum-com** [comment]
@rav3n11  can you add some more description i want to work on it.

**Comment by rav3n11** [comment]
Okay... so, right now, we randomly pick colors for the skinColor, torsoColor and pantsColor from an array. With the updated frontend, users will be able to pick the colors themselves. we need a route that receives a request with a JSON body with fields : **skinColor**, **torsoColor** and **pantsColor** and responds with a generated svg. see [generate.js](https://github.com/rav3n11/lego-minifig-generator/blob/main/generate.js)

**Comment by zaahmed-nisum-com** [comment]
@rav3n11  got it please assign it to me, will start working on it

**Comment by brookmg** [comment]
mtsm ተቀድምሽ አባቱ

**Comment by rav3n11** [comment]
thanks @brookmg
